<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>TorqueScript Syntax: version 1.0</string>
	<key>fileTypes</key>
	<array>
		<string>cs</string>
		<string>gui</string>
		<string>mis</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>TorqueScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Single line comment</string>
			<key>match</key>
			<string>\/\/.*</string>
			<key>name</key>
			<string>comment.line.double-slash.torque</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\/\*</string>
			<key>comment</key>
			<string>Multiple line comment</string>
			<key>end</key>
			<string>\*\/</string>
			<key>name</key>
			<string>comment.block.torque</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Global variable</string>
			<key>match</key>
			<string>\$[a-zA-Z_][0-9a-zA-Z_]*(:+[0-9a-zA-Z_]+)*\b</string>
			<key>name</key>
			<string>variable.other.global.torque</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Local variable</string>
			<key>match</key>
			<string>%[a-zA-Z_][0-9a-zA-Z_]*(:+[0-9a-zA-Z_]+)*\b</string>
			<key>name</key>
			<string>variable.other.local.torque</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>String</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.double.torque</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped-char</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.torque</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>comment</key>
			<string>Tagged String</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.single.torque</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped-char</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.torque</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Control Structure</string>
			<key>match</key>
			<string>\b(switch\$)|\b(break|case|continue|default|else|for|if|return|switch|while)\b</string>
			<key>name</key>
			<string>keyword.control.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:parent(?=::))</string>
			<key>name</key>
			<string>keyword.other.parent.torque</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>String Operator</string>
			<key>match</key>
			<string>@|SPC|TAB|NL</string>
			<key>name</key>
			<string>keyword.operator.string.torque</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Logical Operator</string>
			<key>match</key>
			<string>(!|&amp;&amp;|\|\|)</string>
			<key>name</key>
			<string>keyword.operator.logical.torque</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Compound Assignment Operator</string>
			<key>match</key>
			<string>(\+|\-|\*|\/|%|\&amp;|\||\^|&lt;&lt;|&gt;&gt;)=</string>
			<key>name</key>
			<string>keyword.operator.compound-assignment.torque</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Bitwise Operator</string>
			<key>match</key>
			<string>(\~|\&amp;|\||\^|&lt;&lt;|&gt;&gt;)</string>
			<key>name</key>
			<string>keyword.operator.bitwise.torque</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comparison Operator</string>
			<key>match</key>
			<string>(&lt;|&gt;|&lt;=|&gt;=|==|!=|\$=|!\$=)</string>
			<key>name</key>
			<string>keyword.operator.comparison.torque</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Arithmetic Operator</string>
			<key>match</key>
			<string>(\-|\+|\*|\/|%|\+\+|\-\-)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.torque</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Assignment Operator</string>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string>keyword.operator.assignment.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>::</string>
			<key>name</key>
			<string>keyword.operator.scope-resolution.torque</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.torque</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.namespace.torque</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.torque</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function</string>
			<key>match</key>
			<string>(?:^\s*)(function)\s*(?:([a-zA-Z0-9_]+)::)?([a-zA-Z0-9_]+)\s*\(</string>
			<key>name</key>
			<string>meta.function.torque</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:^\s*)(datablock)\s*([a-zA-Z0-9_]+)\s*\(\s*([a-zA-Z0-9_]+)?(?:\s*\:\s*([a-zA-Z0-9_]+))?\s*\)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.datablock.torque</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.datablock.torque</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.datablock.torque</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.cloned.datablock.torque</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>DataBlock</string>
			<key>end</key>
			<string>\{</string>
			<key>name</key>
			<string>meta.datablock.torque</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.package.torque</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.package.torque</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Package</string>
			<key>match</key>
			<string>(?:^\s*)(package)\s*([a-zA-Z0-9_]+)</string>
			<key>name</key>
			<string>meta.package.torque</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.new.torque</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.object.torque</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.object.torque</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.cloned.object.torque</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(new)\s+([a-zA-Z0-9_]+)\s*\(\s*([a-zA-Z0-9_]+)?(?:\s*\:\s*([a-zA-Z0-9_]+))?\s*[,\)]</string>
			<key>name</key>
			<string>meta.newobject.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bnew\b</string>
			<key>name</key>
			<string>keyword.operator.new.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(function|datablock|package)\b</string>
			<key>name</key>
			<string>storage.type.torque</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Boolean Constant</string>
			<key>match</key>
			<string>TRUE|true|FALSE|false</string>
			<key>name</key>
			<string>constant.language.boolean.torque</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Hexadecimal Number</string>
			<key>match</key>
			<string>0x[0-9a-fA-F]+</string>
			<key>name</key>
			<string>constant.numeric.hexadecimal.torque</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numeric Constant</string>
			<key>match</key>
			<string>\b-?\d+(\.\d+)?([Ee]-?\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:bind(Cmd)?|get(Binding|Command|DeadZone|Scale)|isInverted|p(op|ush)|save|unbind)\b</string>
			<key>name</key>
			<string>support.function.action-map.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:getAddress|(get|set)(FreeLook|Move|Trigger))\b</string>
			<key>name</key>
			<string>support.function.ai-connection.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:setPowerAudioProfiles)\b</string>
			<key>name</key>
			<string>support.function.ambient-audio-manager.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:ai(AddPlayer|Connect)|clearAim|(get|set)(Aim(Location|Object)|MoveDestination)|setMoveSpeed|stop)\b</string>
			<key>name</key>
			<string>support.function.ai-player.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(get|set)MoveDestination|setMove(Speed|Tolerance)|stop)\b</string>
			<key>name</key>
			<string>support.function.ai-wheeled-vehicle.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:getPosition|set(FlyMode|OrbitMode))\b</string>
			<key>name</key>
			<string>support.function.camera.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:init)\b</string>
			<key>name</key>
			<string>support.function.debris.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:setBookmark|gotoBookmark)\b</string>
			<key>name</key>
			<string>support.function.edit-manager.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:close|isEOF|open(ForAppend|ForRead|ForWrite)|(read|write)Line)\b</string>
			<key>name</key>
			<string>support.function.file-object.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:startFoliageReplication)\b</string>
			<key>name</key>
			<string>support.function.fx-foliage-replicator.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(attachTo|detachFrom)Object|reset|setEnable)\b</string>
			<key>name</key>
			<string>support.function.fx-light.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:startClientReplication)\b</string>
			<key>name</key>
			<string>support.function.fx-shape-replicator.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:reset|set((Azimuth|Blue|Brightness|Elevation|Green|Red|Rotation|SingleColour|Size)Keys|(Azimuth|Brightness|Colour|Elevation|Fade|Rotation|Size)Time|BlendMode|Enable|Flare(Bitmaps|Brightness|Colour|Size|TP)|LinkFlareSize|(Lerp|Max|Min|Use)(Azimuth|Brightness|Colour|Elevation|Rotation|Size)|Sun(Azimuth|Elevation)))\b</string>
			<key>name</key>
			<string>support.function.fx-sun-light.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(get|set)DataBlock)\b</string>
			<key>name</key>
			<string>support.function.game-base.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:activateGhosting|chaseCam|clearCameraObject|delete|get((Camera|Control)Object|ControlCameraFov|ServerConnection)|is(AIControlled|Demo(Playing|Recording)|FirstPerson)|listClassIDs|play(2D|3D|Demo)|resetGhosting|set(BlackOut|CameraObject|ConnectArgs|Control(CameraFov|Object)|FirstPerson|JoinPassword|MissionCRC)|(start|stop)Recording|transmitDataBlocks)\b</string>
			<key>name</key>
			<string>support.function.game-connection.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(activate|deactivate)Light|echoTriggerableLights|getNumDetailLevels|magicButton|set(AlarmMode|DetailLevel|SkinBase))\b</string>
			<key>name</key>
			<string>support.function.interior-instance.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:getLastSticky(Normal|Pos)|is(Rotating|Static)|setCollisionTimeout)\b</string>
			<key>name</key>
			<string>support.function.item.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:strike(Object|RandomPoint)|warningFlashes)\b</string>
			<key>name</key>
			<string>support.function.lightning.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:checkMaxRate|clear(Server)?Paths|connect|connectLocal|get(Address|Ghost(ID|sActive)|PacketLoss|Ping)|resolve(GhostID|ObjectFromGhostIndex)|setSimulatedNetParams|transmitPaths|getPathID)\b</string>
			<key>name</key>
			<string>support.function.mission-area.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:clearScopeToClient|getGhostId|scopeToClient|setScopeAlways)\b</string>
			<key>name</key>
			<string>support.function.net-object.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:popFront|push(Back|Front)|reset|set(Position|State|Target))\b</string>
			<key>name</key>
			<string>support.function.path-camera.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:activate|deactivate)\b</string>
			<key>name</key>
			<string>support.function.physical-zone.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:checkDismountPoint|(clear|set)ControlObject|get(ControllingObject|DamageLocation|State)|setActionThread)\b</string>
			<key>name</key>
			<string>support.function.player.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:modifyStorm|setPercentage)\b</string>
			<key>name</key>
			<string>support.function.precipitation.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:get(ForwardVector|ObjectBox|Position|Scale|Transform|WorldBox|WorldBoxCenter)|set(Scale|Transform))\b</string>
			<key>name</key>
			<string>support.function.scene-object.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:apply(Damage|Impulse|Repair)|canCloak|get(AIRepairPoint|CameraFov|Controlling(Client|Object)|Damage(Flash|Level|Percent|State)|Energy(Level|Percent)|Eye(Point|Transform|Vector)|Image(Ammo|Loaded|SkinTag|State|Trigger)|Mount(ed(Image|Object|Object(Count|Node))|NodeObject|Slot)|Muzzle(Point|Vector)|ObjectMount|PendingImage|(Recharge|Repair)Rate|(Shape|Skin)Name|SlotTransform|Velocity|WhiteOut)|is(Cloaked|Destroyed|Disabled|Enabled|Hidden|Image(Firing|Mounted)|Mounted)|mount(Image|Object)|pauseThread|play(Audio|Thread)|set(CameraFov|Cloaked|Damage(Flash|Level|State|Vector)|EnergyLevel|Hidden|Image(Ammo|Loaded|Trigger)|InvincibleMode|(Recharge|Repair)Rate|(Shape|Skin)Name|ThreadDir|Velocity|WhiteOut|ShadowDetailLevel)|startFade|stopAudio|stopThread|unmount|unmount(Image|Object))\b</string>
			<key>name</key>
			<string>support.function.shape-base.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:checkDeployPos|getDeployTransform)\b</string>
			<key>name</key>
			<string>support.function.shape-base-data.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:findObjectByInternalName)\b</string>
			<key>name</key>
			<string>support.function.sim-group.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:delete|dump|get(ClassName|Group|Id|(Internal)?Name|Type)|isMethod|save|schedule|set(Internal)?Name)\b</string>
			<key>name</key>
			<string>support.function.sim-object.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:add|bringToFront|clear|get(Count|Object)|isMember|listObjects|pushToBack|remove)\b</string>
			<key>name</key>
			<string>support.function.sim-set.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(get|set)WindVelocity|realFog|storm(Clouds|Fog)|storm(Clouds|Fog)Show)\b</string>
			<key>name</key>
			<string>support.function.sky.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(get|set)PoweredState)\b</string>
			<key>name</key>
			<string>support.function.static-shape.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:connect|disconnect|listen|send)\b</string>
			<key>name</key>
			<string>support.function.tcp-object.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(get|set)(HeightfieldScript|TextureScript)|save)\b</string>
			<key>name</key>
			<string>support.function.terrain-block.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:get(NumObjects|Object))\b</string>
			<key>name</key>
			<string>support.function.trigger.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:getWheelCount|setWheel(Powered|Spring|Steering|Tire))\b</string>
			<key>name</key>
			<string>support.function.wheeled-vehicle.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:alx(CreateSource|Get(ChannelVolume|Listenerf|Source(f|i|3f)|Stream(Duration|Position)|WaveLen)|Listener(3)?f|IsPlaying|Play|SetChannelVolume|Source(f|i|3f)|Stop|StopAll)|al(Listener3f|Get(Listener(i|3f)|String|WaveLen))|OpenAL(InitDriver|ShutdownDriver|RegisterExtensions))\b</string>
			<key>name</key>
			<string>support.function.openal.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:debug|dbg(IsConnected|Disconnect)|dumpConsole(Classes|Functions)|setEchoFileLoads)\b</string>
			<key>name</key>
			<string>support.function.debugging.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:setInteriorRenderMode)\b</string>
			<key>name</key>
			<string>support.function.interiors.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(play|save)Journal)\b</string>
			<key>name</key>
			<string>support.function.journaling.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:inputLog|setLogMode)\b</string>
			<key>name</key>
			<string>support.function.logging.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:dumpUnflaggedAllocs|flagCurrentAllocs|freeMemoryDump|getMaxFrameAllocation)\b</string>
			<key>name</key>
			<string>support.function.memory.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:GLEnable(Logging|Metrics)|metrics)\b</string>
			<key>name</key>
			<string>support.function.metrics.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:dbgSetParameters|dNetSetLogging)\b</string>
			<key>name</key>
			<string>support.function.networking.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:profiler(Dump|DumpToFile|Enable|MarkerEnable|Reset))\b</string>
			<key>name</key>
			<string>support.function.profiling.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:backtrace|trace)\b</string>
			<key>name</key>
			<string>support.function.tracing.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:addBadWord|containsBadWords|filterString|str(i?cmp|(lw|up)r|len|replace|chr|pos|str)|(get|remove|set)(Field|Record)|(getField|getRecord)(Count|s)|getSubStr|strip(Chars|ColorCodes|MLControlChars|TrailingSpaces)|(l|r)?trim|nextToken|(first|get|remove|set)Word|getWordCount|(get|rest)Words|(add|build|get|remove)TaggedString|detag|dumpNetStringTable|getTag)\b</string>
			<key>name</key>
			<string>support.function.strings.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:gotoWebPage|setNetPort|telnetSetParameters)\b</string>
			<key>name</key>
			<string>support.function.telnet.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:commandTo(Client|Server)|msg)\b</string>
			<key>name</key>
			<string>support.function.client-server.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:allowConnections|(stop|cancel)ServerQuery|getServerCount|query(LANServers|(Master|Single)Server)|setServerInfo|(start|stop)Heartbeat)\b</string>
			<key>name</key>
			<string>support.function.game-server.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:call|cls|collapseEscape|compile|deleteVariables|echo|enableWinConsole|error|eval|exec|expandEscape|export|quit(WithErrorMessage)?|warn|isFunction)\b</string>
			<key>name</key>
			<string>support.function.console.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(de)?activate(DirectInput|Keyboard)|(dis|en)able(Joystick|Mouse)|(echo|toggle)InputState|getJoystickAxes|isJoystickDetected|lockMouse)\b</string>
			<key>name</key>
			<string>support.function.device-io.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:createPath|expandFileName|file(Base|Ext|Name|Path|Delete|Size)|find(FirstFile(MultiExpr)?|NextFile(MultiExpr)?)|get(WorkingDirectory|DirectoryList|ExecutableName|File(Count(MultiExpr)?|CRC))|is(File|WriteableFileName)|pathCopy|(save|load)ChunkFile)\b</string>
			<key>name</key>
			<string>support.function.file-io.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:populate(All)?FontCache(String|Range)|dumpFontCacheStatus|writeFontCache|(export|import|duplicate)CachedFont)\b</string>
			<key>name</key>
			<string>support.function.font-cache.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(set|increase|decrease)FSAA)\b</string>
			<key>name</key>
			<string>support.function.mac-fsaa.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(de)?activatePackage|isPackage)\b</string>
			<key>name</key>
			<string>support.function.packages.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:isObject|nameToID|strToPlayerName|getVariable|restartInstance)\b</string>
			<key>name</key>
			<string>support.function.objects.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:cancel|get(EventTimeLeft|ScheduleDuration|TimeSinceStart)|isEventPending|schedule)\b</string>
			<key>name</key>
			<string>support.function.event-schedulling.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:deleteDataBlocks)\b</string>
			<key>name</key>
			<string>support.function.datablocks.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:addMaterialMapping|clearTextureHolds|dumpTextureStats|flushTextureCache|get(DesktopResolution|DisplayDeviceList|Res(olutionList)?|VideoDriverInfo)|is(DeviceFullScreenOnly|FullScreen)|(next|prev)Resolution|png2jpg|(panorama)?screenShot|set(DefaultFov|DisplayDevice|Fov|OpenGL(Anisotropy|(Interior|Sky)?MipReduction|TextureCompressionHint)|Res|ScreenMode|VerticalSync)|switchBitDepth|toggleFullScreen|videoSetGammaCorrection|minimizeWindow|dumpDisplayIDs|test(WindowLevels|SetWindowTitle)|invertScreenColor|testAsserts)\b</string>
			<key>name</key>
			<string>support.function.video-texturing.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:calcExplosionCoverage|get(ControlObjectAltitude|ControlObjectSpeed|Clipboard|ModPaths|TerrainHeight)|isPointInside|pathOnMissionLoadDone|makeTestTerrain|dPathCopy|testAlert|set(ModPaths|Clipboard|ZoomSpeed)|_sg(Create|Drop)Decal|sgLightingModel(Count|Name))\b</string>
			<key>name</key>
			<string>support.function.special.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:redbook(Open|Close|Play|Stop|Get(TrackCount|Volume|Device(Count|Name)|LastError)|SetVolume))\b</string>
			<key>name</key>
			<string>support.function.redbook-audio.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:dumpResourceStats|purgeResources)\b</string>
			<key>name</key>
			<string>support.function.resource-manager.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:lightScene|resetLighting)\b</string>
			<key>name</key>
			<string>support.function.scene.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:container(BoxEmpty|Find(First|Next)|RayCast|Search(Curr(Radius)?Dist|Next))|initContainerRadiusSearch)\b</string>
			<key>name</key>
			<string>support.function.containers-raycast.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:snapToggle)\b</string>
			<key>name</key>
			<string>support.function.editors.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:get(BuildString|CompileTimeString|Version(Number|String))|isDebugBuild)\b</string>
			<key>name</key>
			<string>support.function.build.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:get(Real|Sim)Time)\b</string>
			<key>name</key>
			<string>support.function.time.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:create(Effect)?Canvas)\b</string>
			<key>name</key>
			<string>support.function.guis.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:get(BoxCenter|Random|RandomSeed)|m(Abs|Acos|Asin|Atan|Ceil|Cos|DegToRad|FloatLength|Floor|Log|Pow|RadToDeg|Sin|Solve(Cubic|Quadratic|Quartic)|Sqrt|Tan)|mathInit|matrix(Create(FromEuler)?|Mul(Point|tiply|Vector))|setRandomSeed|vector(Add|Cross|Dist|Dot|Len|Normalize|OrthoBasis|Scale|Sub))\b</string>
			<key>name</key>
			<string>support.function.math.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:set(Bitmap|Value))\b</string>
			<key>name</key>
			<string>support.function.gui-bitmap-ctrl.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(get|set)Text|performClick)\b</string>
			<key>name</key>
			<string>support.function.gui-button-base-ctrl.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:cursor(On|Off)|get(Content|CursorPos)|hideCursor|isCursorOn|pop(Dialog|Layer)|pushDialog|renderFront|repaint|reset|set(Content|Cursor(Pos)?)|showCursor|setCanvasTitle|(get|set)CoreLangTable)\b</string>
			<key>name</key>
			<string>support.function.gui-canvas.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:get((Min)?Extent|Position|Value)|is(Active|Awake|Visible)|makeFirstResponder|resize|set(Active|Profile|Value|Visible))\b</string>
			<key>name</key>
			<string>support.function.gui-control.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(get|set)Value|identity)\b</string>
			<key>name</key>
			<string>support.function.gui-filter-ctrl.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:addMenu(Item)?|clearMenu(s|Items)|removeMenu(Item)?|setMenuItem(Bitmap|Checked|Enable|Text|Visible)|setMenu(Text|Visible))\b</string>
			<key>name</key>
			<string>support.function.gui-menu-bar.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(at|de)tach)\b</string>
			<key>name</key>
			<string>support.function.gui-message-vector-ctrl.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:clear|deleteLine|dump|getLine(IndexByTag|Tag|Text|TextByTag)|getNumLines|insertLine|(pop|push)(Back|Front)Line)\b</string>
			<key>name</key>
			<string>support.function.message-vector.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:addText|forceReflow|getText|scrollTo(Tag|Top)|set(Alpha|CursorPosition|Text))\b</string>
			<key>name</key>
			<string>support.function.gui-ml-text-ctrl.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:add(Scheme)?|clear|findText|force(Close|OnAction)|get(Selected|Text(ByID)?|)|replaceText|set(EnumContent|Selected|Text)|size|sort)\b</string>
			<key>name</key>
			<string>support.function.gui-popup-menu-ctrl.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:scrollTo(Bottom|Top))\b</string>
			<key>name</key>
			<string>support.function.gui-scroll-ctrl.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:getValue)\b</string>
			<key>name</key>
			<string>support.function.gui-slider-ctrl.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:setText)\b</string>
			<key>name</key>
			<string>support.function.gui-text-ctrl.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(get|set)CursorPos)\b</string>
			<key>name</key>
			<string>support.function.gui-text-edit-ctrl.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:addRow|clear(Selection)?|findTextIndex|get(Row(ID|NumByID|Text|TextByID)|SelectedID)|isRowActive|removeRow(ByID)?|rowCount|scrollVisible|set(Row(Active|ByID)|Selected(Row|ByID))|sort(Numerical)?)\b</string>
			<key>name</key>
			<string>support.function.gui-text-list-ctrl.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(add|remove)(Column|Row)|frame(Border|MinExtent|Movable)|get(Column|Row)(Count|Offset)|set(Column|Row)Offset)\b</string>
			<key>name</key>
			<string>support.function.gui-frameset-ctrl.torque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:on(Action|Add|Cancel|Collision|Damage|DeleteKey|Destroyed|(En|Dis)abled|EndSequence|(Enter|Leave)(Liquid|MissionArea|Trigger)|Exit|Explode|Impact|InputEvent|Menu(Item)?Select|Mount|MoveStuck|Mouse((Right)?Down|(Right)?Dragged|Enter|Leave|Move|(Right)?Up)|NewDataBlock|Node|ReachDestination|Remove|Resize|Select|Sleep|StickyCollision|TabComplete|Target(Enter|Exit)LOS|(Tick)?Trigger|TriggerTick|Unmount|URL|Wake)|animationDone|applyDamage|click|create|doDismount|urlClickCallback)\b</string>
			<key>name</key>
			<string>support.other.callback.torque</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escaped-char</key>
		<dict>
			<key>match</key>
			<string>\\(n|r|t|\\|c\d|cr|cp|co|x[0-9a-fA-F]{2})</string>
			<key>name</key>
			<string>constant.character.escape.torque</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.torque</string>
	<key>uuid</key>
	<string>AD4AAAE0-EB7C-43CA-B5C4-1970FA95CE49</string>
</dict>
</plist>
